<b> Info </b> working in anaconda's PySyft virtual enviroment (that supports Python >= 3.6 and PyTorch 1.1.0).
<a ref="https://github.com/OpenMined/PySyft">Click here to read the documentation</a>

In [11]:
import torch
import numpy as np

### 1. Creating a simple database of 5k entries (e.g. clients)

In [16]:
entries=5000
db = torch.rand(entries) >0.5    # >0.5 round to 1, viceversa round to 0
db

tensor([1, 0, 1,  ..., 1, 1, 0], dtype=torch.uint8)

In [18]:
db.size()   #cross-checking

torch.Size([5000])

### 2. From database create a parallel database with 4999 entries by writing a function.

In [56]:
db_example = torch.rand(10) > 0.5    #creating a small database to start 
db_example
len(db_example)  

10

In [57]:
db_example.dtype

torch.uint8

In [58]:
db_example_i = torch.cat([db_example[:i], db_example[i+1:]])#removing the item with index i and concatenating the tensor slices

In [59]:
db_example_7 = torch.cat([db_example[:7], db_example[8:]])
db_example_7
len(db_example_7) #cross check-yes item was successfully removed and a parallel database was created

9

In [60]:
entries=5000
db=torch.rand(entries) >0.5
 
def parallel_db(db, i):                #parallel_db function with db and item with i-index (to be removed) as arguments 
    return torch.cat([db[:i], db[i+1:]])

In [61]:
parallel_db(db, 10)
len(parallel_db(db, 10))  #cross-check

4999

### 3. Creating a function for list of parallel databases. Each database is smaller of 1 entry than the original database is originated from.

In [102]:
def list_parallel_dbs(db):
    list_dbs=[]
    for i in range(len(db)):
        list_dbs.append(parallel_db(db, i))
    return list_dbs   

In [103]:
list_parallel_dbs(db)  

[tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1

In [104]:
len(list_parallel_dbs(db))  #5000 tensors are created

5000

In [112]:
len(list_parallel_dbs(db)[0])   #the length of one new database is 4999 and I have created created 5000 of these new databases

4999